ipAddr: "192.168.126.128"
server:
  port: 25000

spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: ${ipAddr}
  rabbitmq:
    virtual-host: /
    host: ${ipAddr}
  thymeleaf:
    cache: false
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
    #    scheduling:
    #      pool:
    #        size: 5
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug