ipAddr: 192.168.126.128

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.126.128:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5tHQgyX7b3CTsMt6q4yY
      secret-key: ofEpH6gUPqrQF6tIfI45JJHQoyLFWc
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.126.128
    port: 6379

  rabbitmq:
    host: ${ipAddr}
    port: 5672
    # 指定虚拟主机
    virtual-host: /
    username: guest
    password: guest
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 returnconfirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual
    # 开启发送端确认
    publisher-confirms: true




mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1   #逻辑删除配置
      logic-not-delete-value: 0

server:
  port: 21000

logging:
  level:
    com.junting.gulimall: debug

gulimall:
  thread:
    core-size: 20  # 20-50
    max-size: 200
    keep-alive-time: 10  # 10s

