spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5tHQgyX7b3CTsMt6q4yY
      secret-key: ofEpH6gUPqrQF6tIfI45JJHQoyLFWc
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: minizeng123


server:
  port: 4000