spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5tHQgyX7b3CTsMt6q4yY
      secret-key: ofEpH6gUPqrQF6tIfI45JJHQoyLFWc
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: minizeng123
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        skin: 2e65b1bb3d054466b82f0c9d125465e2
        sign: 908e94ccf08b4476ba6c876d13f084ad
        appCode:

server:
  port: 4000