ipAddr: 192.168.126.129
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8333
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
server:
  port: 40000
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10